version: 2

project_name: ccq

before:
  hooks:
    # Download pre-built DuckDB static libraries
    - bash scripts/download-duckdb-libs.sh

builds:
  - id: ccq
    builder: rust
    dir: ccq
    binary: ccq
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
    # .Target contains the Rust triple (e.g., "x86_64-unknown-linux-gnu")
    # This lets us point to the right DuckDB lib for each target
    env:
      - "DUCKDB_LIB_DIR={{.Env.PWD}}/duckdb-libs/{{.Target}}"
      - "DUCKDB_INCLUDE_DIR={{.Env.PWD}}/duckdb-libs/{{.Target}}"
      - DUCKDB_STATIC=1

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: danny  # Update with actual owner
    name: cc-query
